agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

mongo:
  uri:                  ""
  db_name:              "bug-bounty"
  subdomain_collection: "subdomains"
  program_collection:   "programs"
  vuln_collection:      "vulns"

crawler:
  timeout: 10s
  backoff: 1000ms
  threads: 20
  regexes: 
    - "<script[^>]*src=[\"']?([^\\?#'\" ]*)[\\?#\"']?"
    - "<a[^>]*href=[\"']?([^\\?#'\" ]*)[\\?#\"']?"
  targets_per_subdomain: 20
  min_subdomain_age: 24h

attack:
  timeout: 10s
  backoff: 1000ms
  threads: 300

triage:
  threads: 5


notifications:
  webhook_url: "https://discord.com/api/webhooks/1146615028049522748/Op1A7r0bTAmPLrCMeMD_Iw2rSVtULohfu8zBwzWIAfJnRyoLPSA_TJ38bOV1vHq8CSsS"
  send_status: true
  status_interval: 0
  status_at:
    - "06:30:00"